[package]
name = "mini-screen-core"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
serialport.workspace = true
tiny-skia.workspace = true
fontdue.workspace = true
inventory.workspace = true
sysinfo.workspace = true

chrono.workspace = true

[target.'cfg(windows)'.dependencies]
windows-sys.workspace = true
