[workspace]
resolver = "2"
members = ["core", "cli"]

[workspace.package]
version = "0.1.0"
edition = "2021"
rust-version = "1.85"

[workspace.dependencies]
mini-screen-core = { path = "core" }
serialport = "4.7"
anyhow = "1"
tiny-skia = "0.11"
fontdue = "0.9"
inventory = "0.3"
sysinfo = "0.33"
windows-sys = { version = "0.59", features = ["Win32_Foundation", "Win32_System_Memory"] }
chrono = { version = "0.4", default-features = false, features = ["clock", "std"] }

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
